// This file is auto-generated by @hey-api/openapi-ts

export { getBoard, type Options, postMark } from './sdk.gen';
export type { Board, BoardColumn, Card, ClientOptions, GetBoardData, GetBoardResponse, GetBoardResponses, MarkRequest, MarkResponse, PostMarkData, PostMarkErrors, PostMarkResponse, PostMarkResponses } from './types.gen';
