// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetBoardData, GetBoardResponses, PostMarkData, PostMarkErrors, PostMarkResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Kanban board: environments grouped into status columns.
 */
export const getBoard = <ThrowOnError extends boolean = false>(options?: Options<GetBoardData, ThrowOnError>): RequestResult<GetBoardResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetBoardResponses, unknown, ThrowOnError>({ url: '/api/board', ...options });

/**
 * Set an environment's status. Delegated to the daemon's `env.mark`.
 */
export const postMark = <ThrowOnError extends boolean = false>(options: Options<PostMarkData, ThrowOnError>): RequestResult<PostMarkResponses, PostMarkErrors, ThrowOnError> => (options.client ?? client).post<PostMarkResponses, PostMarkErrors, ThrowOnError>({
    url: '/api/env/mark',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
