// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type Board = {
    columns: Array<BoardColumn>;
};

export type BoardColumn = {
    cards: Array<Card>;
    /**
     * Stable key — also the `status` accepted by `POST /api/env/mark`.
     */
    key: string;
    /**
     * Header label.
     */
    title: string;
};

/**
 * One environment (or not-yet-materialised recipe) shown as a board card.
 */
export type Card = {
    description?: string | null;
    /**
     * True for recipes that have no environment directory yet.
     */
    is_recipe: boolean;
    name: string;
    /**
     * Frecency-derived relevance (the `launcher` percentile `enw ls` computes
     * from usage signals; same ordering semantics as the rofi picker).
     * Columns sort by it descending; the frontend reuses it to keep a moved
     * card's position consistent. Recipes have no usage signals and get 0.
     */
    score: number;
};

export type MarkRequest = {
    env_name: string;
    /**
     * One of: `ready`, `active`, `waiting`, `done`, `evergreen`.
     */
    status: string;
};

export type MarkResponse = {
    ok: boolean;
};

export type GetBoardData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/board';
};

export type GetBoardResponses = {
    200: Board;
};

export type GetBoardResponse = GetBoardResponses[keyof GetBoardResponses];

export type PostMarkData = {
    body: MarkRequest;
    path?: never;
    query?: never;
    url: '/api/env/mark';
};

export type PostMarkErrors = {
    /**
     * daemon rejected the request (invalid status, unknown env)
     */
    400: unknown;
    /**
     * daemon unreachable
     */
    502: unknown;
};

export type PostMarkResponses = {
    200: MarkResponse;
};

export type PostMarkResponse = PostMarkResponses[keyof PostMarkResponses];
