// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { getBoard, type Options, postMark } from '../sdk.gen';
import type { GetBoardData, GetBoardResponse, PostMarkData, PostMarkResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getBoardQueryKey = (options?: Options<GetBoardData>) => createQueryKey('getBoard', options);

/**
 * Kanban board: environments grouped into status columns.
 */
export const getBoardOptions = (options?: Options<GetBoardData>) => queryOptions<GetBoardResponse, DefaultError, GetBoardResponse, ReturnType<typeof getBoardQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getBoard({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getBoardQueryKey(options)
});

/**
 * Set an environment's status. Delegated to the daemon's `env.mark`.
 */
export const postMarkMutation = (options?: Partial<Options<PostMarkData>>): UseMutationOptions<PostMarkResponse, DefaultError, Options<PostMarkData>> => {
    const mutationOptions: UseMutationOptions<PostMarkResponse, DefaultError, Options<PostMarkData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postMark({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
